mixed-port: 65222
tcp-concurrent: true
allow-lan: false
ipv6: true
log-level: info

rules:
  - MATCH,DIRECT

listeners:
  - name: anytls-in
    type: anytls
    port: 443
    listen: "::"
    users:
      974fdc85: 0cdfe9f1b663
    certificate: ./server.crt
    private-key: ./server.key
